import '../../api/quizes/server/publication';
import '../../api/quizes/server/methods';
import '../../api/tags/server/publication';
import '../../api/tags/server/methods';
import '../../api/games/server/publication';
import '../../api/games/server/methods';
import '../../api/users/server/publications';
import '../../api/users/server/methods';
import '../../api/images/server/publication';
